#!/usr/bin/env python
from gevent.wsgi import WSGIServer
from werkzeug.serving import run_with_reloader
from kalerator.web_app import app


app.config['DEBUG'] = True


@run_with_reloader
def run_server():
    ws = WSGIServer(listener=('0.0.0.0', 5000), application=app)
    print ' * Listening on http://0.0.0.0:5000/'
    ws.serve_forever()


if __name__ == "__main__":
    run_server()
